[build]
  publish = "client/dist"  # Path to the 'dist' folder in your 'client' directory
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
