[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://iwdrodqpyisgvdtzgeml.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3ZHJvZHFweWlzZ3ZkdHpnZW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjk4NTksImV4cCI6MjA2MTk0NTg1OX0.HBcMnVGuG7fLaCallp6TTRYOhBtoh3SAOFZnngF_A1s"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 